export const depositLabels = [
  "Deposit Request",
  "Document Submission",
  "Payment",
  "Dispatched",
  "Processing",
  "Deposited",
];
export const customStyles = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: globalColors.PRIMARY_COLOR,
  stepStrokeWidth: 0,
  stepStrokeFinishedColor: globalColors.PRIMARY_COLOR,
  stepStrokeUnFinishedColor: globalColors.GRAY,
  separatorFinishedColor: globalColors.PRIMARY_COLOR,
  separatorUnFinishedColor: globalColors.GRAY,
  stepIndicatorFinishedColor: globalColors.PRIMARY_COLOR,
  stepIndicatorUnFinishedColor: globalColors.GRAY,
  stepIndicatorCurrentColor: "#ffffff",
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 16,
  stepIndicatorLabelCurrentColor: globalColors.PRIMARY_COLOR,
  stepIndicatorLabelFinishedColor: "#ffffff",
  stepIndicatorLabelUnFinishedColor: "#aaaaaa",
  labelColor: globalColors.PRIMARY_COLOR,
  labelSize: 16,
  currentStepLabelColor: globalColors.SECONDARY_COLOR,
};
