import * as yup from "yup";
export const AddMicroorganismFormData = [
  {
    id: "CoreDataSets",
    title: "Core Data Sets",
    elements: [
      { id: "Genus", placeholder: "Genus", type: "text" },
      { id: "AccessionNumber", placeholder: "Accession Number", type: "text" },
      {
        id: "OtherCollectionNumbers",
        placeholder: "Other Collection Numbers",
        type: "text",
      },
      { id: "SpeciesEpithet", placeholder: "Species Epithet", type: "text" },
      { id: "Author", placeholder: "Author", type: "text" },
      { id: "OrganismType", placeholder: "Organism Type", type: "text" },
      {
        id: "HistoryOfDeposit",
        placeholder: "History of Deposit",
        type: "text",
      },
      {
        id: "DateOfIsolation",
        placeholder: "Date of Isolation (mm/dd/yyyy)",
        type: "text",
      },
      { id: "IsolatedFrom", placeholder: "Isolated From", type: "text" },
      {
        id: "GeographicOrigin",
        placeholder: "Geographic Origin",
        type: "text",
      },
      { id: "Status", placeholder: "Status", type: "text" },
      {
        id: "OptimumGrowthTemperature",
        placeholder: "Optimum Growth Temperature",
        type: "number",
      },
      {
        id: "MaximumGrowthTemperature",
        placeholder: "Maximum Growth Temperature",
        type: "number",
      },
      {
        id: "MinimumGrowthTemperature",
        placeholder: "Minimum Growth Temperature",
        type: "number",
      },
      { id: "Medium", placeholder: "Medium", type: "text" },
      { id: "Application", placeholder: "Application", type: "text" },
      { id: "Literature", placeholder: "Literature", type: "text" },
    ],
    validationSchema: yup.object({
      CoreDataSets: yup.object({
        Genus: yup.string().required("Required"),
        AccessionNumber: yup.string().required("Required"),
        SpeciesEpithet: yup.string().required("Required"),
        Author: yup.string().required("Required"),
        OrganismType: yup.string().required("Required"),
        HistoryOfDeposit: yup.string().required("Required"),
        DateOfIsolation: yup.date("Must be a valid date").required("Required"),
        IsolatedFrom: yup.string().required("Required"),
        GeographicOrigin: yup.string().required("Required"),
        Status: yup.string().required("Required"),
        Medium: yup.string().required("Required"),
        OptimumGrowthTemperature: yup.number().required("Required"),
        MaximumGrowthTemperature: yup.number().required("Required"),
        MinimumGrowthTemperature: yup.number().required("Required"),
      }),
    }),
  },
  {
    id: "Name",
    title: "Name",
    elements: [
      {
        id: "TaxonomyID",
        placeholder: "Taxonomy ID",
        type: "number",
      },
    ],
    validationSchema: yup.object({
      Name: yup.object({
        TaxonomyID: yup.number().required("Required"),
      }),
    }),
  },
  {
    id: "StrainAdministration",
    title: "Strain Administration",
    elements: [
      {
        id: "DateOfAccession",
        placeholder: "Date of Accession (mm/dd/yyyy)",
        type: "number",
      },
      { id: "HerbariumNo", placeholder: "Herbarium No", type: "number" },
      {
        id: "InternalIdentityCheck",
        placeholder: "Internal Identity Check",
        type: "text",
      },
      {
        id: "ModeOfPreservation",
        placeholder: "Mode of Preservation",
        type: "text",
      },
      { id: "BioHazardLevel", placeholder: "Bio Hazard Level", type: "text" },
      {
        id: "RestrictionRemarks",
        placeholder: "Restriction Remarks",
        type: "text",
      },
      { id: "CountryOfExport", placeholder: "Country of Export", type: "text" },
      { id: "MTA", placeholder: "MTA", type: "text" },
      {
        id: "DistributionRestriction",
        placeholder: "Distribution Restriction",
        type: "text",
      },
      {
        id: "AnimalQuarantineNo",
        placeholder: "Animal Quarantine No",
        type: "text",
      },
      {
        id: "PlantQuarantineNo",
        placeholder: "Plant Quarantine No",
        type: "text",
      },
      { id: "FormOfSupply", placeholder: "Form of Supply", type: "text" },
    ],
    validationSchema: yup.object({
      StrainAdministration: yup.object({
        //     DateOfAccession:yup.date().required("Required"),
        //     HerbariumNo: yup.number().required("Required"),
        //   InternalIdentityCheck: yup.string().required("Required"),
        //   ModeOfPreservation: yup.string().required("Required"),
        //   BioHazardLevel: yup.number().required,
        //   RestrictionRemarks: yup.string().required("Required"),
        //   CountryOfExport: yup.string().required("Required"),
        //   MTA: yup.string().required("Required"),
        //   DistributionRestriction: yup.string().required("Required"),
        //   AnimalQuarantineNo: yup.string().required("Required"),
        //   PlantQuarantineNo: yup.string().required("Required"),
        //   FormOfSupply: yup.string().required("Required"),
      }),
    }),
  },
  {
    id: "EnviromentAndHistory",
    title: "Enviroment And History",
    elements: [
      { id: "SubStrate", placeholder: "Sub Strate", type: "text" },
      { id: "Habitat", placeholder: "Habitat", type: "text" },
      { id: "Latitude", placeholder: "Latitude", type: "number" },
      { id: "Longitude", placeholder: "Longitude", type: "number" },
      { id: "Altitude", placeholder: "Altitude", type: "number" },
      { id: "Depth", placeholder: "Depth", type: "number" },
      { id: "Humidity", placeholder: "Humidity", type: "number" },
      {
        id: "PHForEnviroment",
        placeholder: "PH for Enviroment",
        type: "number",
      },
      {
        id: "TemperatureForEnviroment",
        placeholder: "Temperature For Enviroment",
        type: "number",
      },
      {
        id: "CollectionMethod",
        placeholder: "Collection Method",
        type: "text",
      },
      {
        id: "DateOfCollection",
        placeholder: "Date of Collection (mm/dd/yyyy)",
        type: "text",
      },
      {
        id: "CountryOfCollection",
        placeholder: "Country of Collection",
        type: "text",
      },
      { id: "State", placeholder: "State", type: "text" },
      {
        id: "RegionOfCollection",
        placeholder: "Region of Collection",
        type: "text",
      },
      { id: "CollectedBy", placeholder: "Collected by", type: "text" },
      { id: "IsolatedBy", placeholder: "Isolated by", type: "text" },
      {
        id: "MethodOfIsolation",
        placeholder: "Method of Isolation",
        type: "text",
      },
      { id: "IdentifiedBy", placeholder: "Identified By", type: "text" },
      {
        id: "DateOfIdentification",
        placeholder: "Date of Identification (mm/dd/yyyy)",
        type: "number",
      },
      { id: "DepositedBy", placeholder: "Deposited By", type: "text" },
      {
        id: "DateOfDeposition",
        placeholder: "Date of Deposition (mm/dd/yyyy)",
        type: "number",
      },
      { id: "NameAtAccept", placeholder: "Name at Accept", type: "text" },
    ],
    validationSchema: yup.object({
      EnviromentAndHistory: yup.object({
        SubStrate: yup.string().nullable(),
        Habitat: yup.string().nullable(),
        Latitude: yup.number().nullable(),
        Longitude: yup.number().nullable(),
        Altitude: yup.number().nullable(),
        Depth: yup.number().nullable(),
        Humidity: yup.number().nullable(),
        PHForEnviroment: yup.number().nullable(),
        TemperatureForEnviroment: yup.number().nullable(),
        CollectionMethod: yup.string().nullable(),
        DateOfCollection: yup.date(),
        CountryOfCollection: yup.string().nullable(),
        State: yup.string().nullable(),
        RegionOfCollection: yup.string().nullable(),
        CollectedBy: yup.string().nullable(),
        IsolatedBy: yup.string().nullable(),
        MethodOfIsolation: yup.string().nullable(),
        IdentifiedBy: yup.string().nullable(),
        DateOfIdentification: yup.date(),
        DepositedBy: yup.string().nullable(),
        DateOfDeposition: yup.date().nullable(),
        NameAtAccept: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "Publication",
    title: "Publication",
    elements: [
      {
        id: "LiteratureCategories",
        placeholder: "Literature Categories",
        type: "text",
      },
      { id: "Title", placeholder: "Title", type: "text" },
      { id: "Author", placeholder: "Author", type: "text" },
      { id: "Journal", placeholder: "Journal", type: "text" },
      { id: "Volume", placeholder: "Volume", type: "text" },
      { id: "Number", placeholder: "Number", type: "text" },
      { id: "StartingPage", placeholder: "Starting Page", type: "text" },
      { id: "EndingPage", placeholder: "Ending Page", type: "text" },
      { id: "PageRange", placeholder: "Page Range", type: "text" },
      { id: "Year", placeholder: "Year", type: "text" },
      { id: "DOINumber", placeholder: "DOI Number", type: "text" },
    ],
    validationSchema: yup.object({
      Publication: yup.object({
        LiteratureCategories: yup.string().nullable(),
        Title: yup.string().nullable(),
        Author: yup.string().nullable(),
        Journal: yup.string().nullable(),
        Volume: yup.number().nullable(),
        Number: yup.number().nullable(),
        StartingPage: yup.number().nullable(),
        PageRange: yup.string().nullable(),
        Year: yup.number().nullable(),
        DOINumber: yup.number().nullable(),
      }),
    }),
  },
  {
    id: "BiologicalInteractions",
    title: "Biological Interactions",
    elements: [
      { id: "Symbiosis", placeholder: "Symbiosis", type: "text" },
      { id: "Microparasitism", placeholder: "Mycoparasitism", type: "text" },
      { id: "Pathogenicity", placeholder: "Pathogenicity", type: "text" },
      { id: "Allergenicity", placeholder: "Allergenicity", type: "text" },
      {
        id: "OtherOrganismsToxicity",
        placeholder: "Other Organism Toxicity",
        type: "text",
      },
      {
        id: "AntagonisticActivities",
        placeholder: "Antagonistic Activities",
        type: "text",
      },
    ],
    validationSchema: yup.object({
      BiologicalInteractions: yup.object({
        Symbiosis: yup.string().nullable(),
        Mycoparasitism: yup.string().nullable(),
        Pathogenicity: yup.string().nullable(),
        Allergenicity: yup.string().nullable(),
        OtherOrganismToxicity: yup.string().nullable(),
        AntagonisticActivities: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "Sexuality",
    title: "Sexuality",
    elements: [
      { id: "SexualBehaviour", placeholder: "Sexual Behaviour", type: "text" },
      { id: "SexualState", placeholder: "Sexual State", type: "text" },
    ],
    validationSchema: yup.object({
      Sexuality: yup.object({
        SexualBehaviour: yup.string().nullable(),
        SexualState: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "Properties",
    title: "Properties",
    elements: [
      { id: "NumberOfNuclei", placeholder: "Number of Nuclei", type: "text" },
      {
        id: "RehyderationFluid",
        placeholder: "Rehyderation Fluid",
        type: "text",
      },
      {
        id: "FineStructureData",
        placeholder: "Fine Structure Data",
        type: "text",
      },
      {
        id: "WallConstituents",
        placeholder: "Wall Constituents",
        type: "text",
      },
      { id: "CellContents", placeholder: "Cell Contents", type: "text" },
      { id: "CoenzymeQSystem", placeholder: "Coenzyme Q System", type: "text" },
      {
        id: "StainingReactions",
        placeholder: "Staining Reactions",
        type: "text",
      },
      {
        id: "PigmentProduction",
        placeholder: "Pigment Production",
        type: "text",
      },
      { id: "CellShape", placeholder: "Cell Shape", type: "text" },
      { id: "CellSize", placeholder: "Cell Size", type: "text" },
      { id: "Motile", placeholder: "Motile", type: "text" },
      { id: "SporeForming", placeholder: "Spore Forming", type: "text" },
      { id: "MotileBy", placeholder: "Motile By", type: "text" },
    ],
    validationSchema: yup.object({
      Properties: yup.object({
        NumberOfNuclei: yup.number().nullable(),
        RehyderationFluid: yup.string().nullable(),
        FineStructureData: yup.string().nullable(),
        WallConstituents: yup.string().nullable(),
        CellContents: yup.string().nullable(),
        CoenzymeQSystem: yup.string().nullable(),
        StainingReactions: yup.string().nullable(),
        PigmentProduction: yup.string().nullable(),
        CellShape: yup.string().nullable(),
        CellSize: yup.string().nullable(),
        Motile: yup.string().nullable(),
        SporeForming: yup.string().nullable(),
        MotileBy: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "GrnotypeAndGenetics",
    title: "Grnotype and Genetics",
    elements: [
      { id: "Genotype", placeholder: "Genotype", type: "text" },
      { id: "Phenotype", placeholder: "Phenotype", type: "text" },
      { id: "MatingType", placeholder: "Mating Type", type: "text" },
      {
        id: "SexualReproduction",
        placeholder: "Sexual Reproduction",
        type: "text",
      },
      { id: "GCContentOfDNA", placeholder: "GC Content of DNA", type: "text" },
      {
        id: "OtherStrainsHybridization",
        placeholder: "Other Strains Hybridization",
        type: "text",
      },
      {
        id: "HybridizationStrainNumber",
        placeholder: "Hybridization Strain Number",
        type: "text",
      },
      { id: "TypeOfDNAOrRNA", placeholder: "Type of DNA or RNA", type: "text" },
      { id: "Percentage", placeholder: "Percentage", type: "text" },
      {
        id: "TemperatureOfHybridization",
        placeholder: "Temperature of Hybridization",
        type: "text",
      },
      { id: "Mutants", placeholder: "Mutants", type: "text" },
      { id: "MutationMethods", placeholder: "Mutation Methods", type: "text" },
      { id: "Hybrids", placeholder: "Hybrids", type: "text" },
      { id: "Plasmid", placeholder: "Plasmid", type: "text" },
      {
        id: "KillerPropertiesOfYeast",
        placeholder: "Killer Properties of Yeast",
        type: "text",
      },
    ],
    validationSchema: yup.object({
      GrnotypeAndGenetics: yup.object({
        Genotype: yup.string().nullable(),
        Phenotype: yup.string().nullable(),
        MatingType: yup.string().nullable(),
        SexualReproduction: yup.string().nullable(),
        GCContentOfDNA: yup.string().nullable(),
        OtherStrainsHybridization: yup.string().nullable(),
        HybridizationStrainNumber: yup.string().nullable(),
        TypeOfDNAOrRNA: yup.string().nullable(),
        Percentage: yup.number().nullable(),
        TemperatureOfHybridization: yup.number().nullable(),
        Mutants: yup.string().nullable(),
        MutationMethods: yup.string().nullable(),
        Hybrids: yup.string().nullable(),
        Plasmid: yup.string().nullable(),
        KillerPropertiesOfYeast: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "GrowthConditions",
    title: "Growth Conditions",
    elements: [
      {
        id: "ConditionsForGrowthAndMaintenenceOnSolidMedia",
        placeholder: "Conditions for Growth and MaintenenceOnSolidMedia",
        type: "text",
      },
      {
        id: "ConditionsForGrowthInLiquidMedia",
        placeholder: "Conditions for Growth in Liquid Media",
        type: "text",
      },
      {
        id: "ConditionsForFruitingOrSporulation",
        placeholder: "Conditions for Fruiting or Sporulation",
        type: "text",
      },
      {
        id: "ConditionsForGermination",
        placeholder: "Conditions for Germination",
        type: "text",
      },
      {
        id: "CarbonSourcesTested",
        placeholder: "Carbon Sources Tested",
        type: "text",
      },
      {
        id: "NitrogenSourcesTested",
        placeholder: "Nitrogen Sources Tested",
        type: "text",
      },
      {
        id: "SingleCompoundsTested",
        placeholder: "Single Compounds Tested",
        type: "text",
      },
      {
        id: "NutritionalRequirements",
        placeholder: "Nutritional Requirements",
        type: "text",
      },
      {
        id: "MetabolitesProduced",
        placeholder: "Metabolites Produced",
        type: "text",
      },
      {
        id: "TolerenceAndSensitivities",
        placeholder: "Tolerence and Sensitivities",
        type: "text",
      },
      { id: "Deficiencies", placeholder: "Deficiencies", type: "text" },
      {
        id: "TolerancesAndSensitivities",
        placeholder: "Tolerances and Sensitivities",
        type: "text",
      },
      {
        id: "TemperatureRelationships",
        placeholder: "Temperature Relationships",
        type: "text",
      },
      { id: "MaximumGrowthPH", placeholder: "Maximum Growth PH", type: "text" },
      { id: "MinimumGrowthPH", placeholder: "Minimum Growth PH", type: "text" },
      { id: "OptimalGrowthPH", placeholder: "Optimal Growth PH", type: "text" },
      { id: "LighConditions", placeholder: "Ligh Conditions", type: "text" },
      {
        id: "OxygenRelationship",
        placeholder: "Oxygen Relationship",
        type: "text",
      },
      { id: "HeatResistence", placeholder: "Heat Resistence", type: "text" },
      {
        id: "EthanolConditions",
        placeholder: "Ethanol Conditions",
        type: "text",
      },
      {
        id: "SalinityRequirements",
        placeholder: "Salinity Requirements",
        type: "text",
      },
      {
        id: "OptimalNaClConcentration",
        placeholder: "Optimal NaCl Concentration",
        type: "text",
      },
      {
        id: "MinimumNaClConcentration",
        placeholder: "Minimum NaCl Concentration",
        type: "text",
      },
      {
        id: "MaximumNaClConcentration",
        placeholder: "Maximum NaCl Concentration",
        type: "text",
      },
      {
        id: "OptimumNaClContentration",
        placeholder: "Optimum NaCl Contentration",
        type: "text",
      },
      {
        id: "OptimumSugarConcentration",
        placeholder: "Optimum Sugar Concentration",
        type: "text",
      },
      {
        id: "MinimumSugarConcentration",
        placeholder: "Minimum Sugar Concentration",
        type: "text",
      },
      {
        id: "MaximumSugarConcentration",
        placeholder: "Maximum Sugar Concentration",
        type: "text",
      },
      {
        id: "OsmophilyAndXerophily",
        placeholder: "Osmophily and Xerophily",
        type: "text",
      },
      {
        id: "WaterActivityConditions",
        placeholder: "Water Activity Conditions",
        type: "text",
      },
    ],
    validationSchema: yup.object({
      GrowthConditions: yup.object({
        ConditionsForGrowthAndMaintenenceOnSolidMedia: yup.string().nullable(),
        ConditionsForGrowthInLiquidMedia: yup.string().nullable(),
        ConditionsForFruitingOrSporulation: yup.string().nullable(),
        ConditionsForGermination: yup.string().nullable(),
        CarbonSourcesTested: yup.string().nullable(),
        NitrogenSourcesTested: yup.string().nullable(),
        SingleCompoundTested: yup.string().nullable(),
        NutritionalRequirements: yup.string().nullable(),
        Deficiencies: yup.string().nullable(),
        TolerancesAndSensitivities: yup.string().nullable(),
        TemperatureRelationships: yup.string().nullable(),
        MaximumGrowthPH: yup.number().nullable(),
        MinimumGrowthPH: yup.number().nullable(),
        OptimalGrowthPH: yup.number().nullable(),
        LighConditions: yup.string().nullable(),
        OxygenRelationship: yup.string().nullable(),
        HeatResistence: yup.string().nullable(),
        EthanolConditions: yup.string().nullable(),
        SalinityRequirements: yup.string().nullable(),
        OptimalNaClConcentration: yup.number().nullable(),
        MinimumNaClConcentration: yup.number().nullable(),
        MaximumNaClConcentration: yup.number().nullable(),
        OptimumSugarConcentration: yup.number().nullable(),
        MinimumSugarConcentration: yup.number().nullable(),
        MaximumSugarConcentration: yup.number().nullable(),
        OsmophilyAndXerophily: yup.string().nullable(),
        WaterActivityConditions: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "ChemistryAndEnzymes",
    title: "Chemistry and Enzymes",
    elements: [
      { id: "EnzymesProduced", placeholder: "Enzymes Produced", type: "text" },
      {
        id: "DecompositionAndDeterioratingCapacities",
        placeholder: "Decomposition and Deteriorating Capacities",
        type: "text",
      },
      {
        id: "MetabolitiesProduced",
        placeholder: "Metabolities Produced",
        type: "text",
      },
      {
        id: "Biotransformations",
        placeholder: "Biotransformations",
        type: "text",
      },
    ],
    validationSchema: yup.object({
      ChemistryAndEnzymes: yup.object({
        EnzymesProduced: yup.string().nullable(),
        DecompositionAndDeterioratingCapacities: yup.string().nullable(),
        MetabolitiesProduced: yup.string().nullable(),
        Biotransformations: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "Medium",
    title: "Medium",
    elements: [
      { id: "Medium", placeholder: "Medium", text: "text" },
      { id: "MediumNumber", placeholder: "Medium Number", text: "text" },
      { id: "MediumName", placeholder: "Medium Name", text: "text" },
      {
        id: "MediumComposition",
        placeholder: "Medium Composition",
        text: "text",
      },
      { id: "MediumPH", placeholder: "Medium PH", text: "text" },
    ],
    validationSchema: yup.object({
      Medium: yup.object({
        MediumNumber: yup.number().nullable(),
        MediumName: yup.string().nullable(),
        MediumComposition: yup.string().nullable(),
        MediumPH: yup.number().nullable(),
      }),
    }),
  },
  {
    id: "Sequence",
    title: "Sequence",
    elements: [
      { id: "AccessionNumber", placeholder: "Accession Number", type: "text" },
      { id: "TargetGene", placeholder: "TargetGene", type: "text" },
      { id: "Definition", placeholder: "Definition", type: "text" },
      {
        id: "SequencingMethod",
        placeholder: "Sequencing Method",
        type: "text",
      },
      { id: "Length", placeholder: "Length", type: "text" },
      { id: "Sequencetype", placeholder: "Sequence Type", type: "text" },
      { id: "Source", placeholder: "Source", type: "text" },
      { id: "Sequence", placeholder: "Sequence", type: "text" },
    ],
    validationSchema: yup.object({
      Sequence: yup.object({
        AccessionNumber: yup.string().nullable(),
        TargetGene: yup.string().nullable(),
        Definition: yup.string().nullable(),
        SequencingMethod: yup.string().nullable(),
        Length: yup.number().nullable(),
        SequenceType: yup.string().nullable(),
        Source: yup.string().nullable(),
        Sequence: yup.string().nullable(),
      }),
    }),
  },
  {
    id: "Catalogue",
    title: "Catalogue",
    elements: [
      { id: "CatalogueName", placeholder: "Catalogue Name", type: "text" },
      { id: "CatalogueURL", placeholder: "Catalogue URL", type: "text" },
      {
        id: "CatalogueUpdateTime",
        placeholder: "Catalogue Update Time (mm/dd/yyyy)",
        type: "text",
      },
      {
        id: "ContactPersonOfCatalogue",
        placeholder: "Contact Person of Catalogue",
        type: "text",
      },
      { id: "ContactEmail", placeholder: "Contact Email", type: "text" },
      { id: "ContactAddress", placeholder: "Contact Address", type: "text" },
      {
        id: "ContactTelephone",
        placeholder: "Contact Telephone",
        type: "text",
      },
      { id: "ContactFax", placeholder: "Contact Fax", type: "text" },
      { id: "NumberOfStrains", placeholder: "Number of Strains", type: "text" },
    ],
    validationSchema: yup.object({
      Catalogue: yup.object({
        CatalogueName: yup.string().nullable(),
        CatalogueURL: yup.string().nullable(),
        CatalogueUpdateTime: yup.string().nullable(),
        ContactPersonOfCatalogue: yup.string().nullable(),
        ContactEmail: yup.string().nullable(),
        ContactAddress: yup.string().nullable(),
        ContactTelephone: yup.number().nullable(),
        ContactFax: yup.string().nullable(),
        NumberOfStrains: yup.number().nullable(),
      }),
    }),
  },
];

export const initalMicroorganismData = {
  CoreDataSets: {
    Genus: "",
    AccessionNumber: "",
    OtherCollectionNumbers: "",
    SpeciesEpithet: "",
    Author: "",
    OrganismType: "Bacteria",
    HistoryOfDeposit: "",
    DateOfIsolation: "",
    IsolatedFrom: "",
    GeographicOrigin: "",
    Status: "Type",
    Medium: "",
    Application: "",
    Literature: "",
    OptimumGrowthTemperature: "",
    MaximumGrowthTemperature: "",
    MinimumGrowthTemperature: "",
  },
  Name: {
    TaxonomyID: "",
  },
  StrainAdministration: {
    DateOfAccession: "",
    HerbariumNo: "",
    InternalIdentityCheck: "",
    ModeOfPreservation: "",
    BioHazardLevel: "1",
    RestrictionRemarks: "",
    CountryOfExport: "",
    MTA: "",
    DistributionRestriction: "",
    AnimalQuarantineNo: "",
    PlantQuarantineNo: "",
    FormOfSupply: "",
  },
  EnviromentAndHistory: {
    SubStrate: "",
    Habitat: "",
    Latitude: "",
    Longitude: "",
    Altitude: "",
    Depth: "",
    Humidity: "",
    PHForEnviroment: "",
    TemperatureForEnviroment: "",
    CollectionMethod: "",
    DateOfCollection: "",
    CountryOfCollection: "",
    State: "",
    RegionOfCollection: "",
    CollectedBy: "",
    IsolatedBy: "",
    MethodOfIsolation: "",
    IdentifiedBy: "",
    DateOfIdentification: "",
    DepositedBy: "",
    DateOfDeposition: "",
    NameAtAccept: "",
  },
  Publication: {
    LiteratureCategories: "",
    Title: "",
    Author: "",
    Journal: "",
    Volume: "",
    Number: "",
    StartingPage: "",
    PageRange: "",
    Year: "",
    DOINumber: "",
  },
  BiologicalInteractions: {
    Symbiosis: "",
    Mycoparasitism: "",
    Pathogenicity: "",
    Allergenicity: "",
    OtherOrganismToxicity: "",
    AntagonisticActivities: "",
  },
  Sexuality: {
    SexualBehaviour: "",
    SexualState: "",
  },
  Properties: {
    NumberOfNuclei: "",
    RehyderationFluid: "",
    FineStructureData: "",
    WallConstituents: "",
    CellContents: "",
    CoenzymeQSystem: "",
    StainingReactions: "Positive",
    PigmentProduction: "",
    CellShape: "",
    CellSize: "",
    Motile: "Motile",
    SporeForming: "",
    MotileBy: "",
  },
  GrnotypeAndGenetics: {
    Genotype: "",
    Phenotype: "",
    MatingType: "",
    SexualReproduction: "",
    GCContentOfDNA: "",
    OtherStrainsHybridization: "",
    HybridizationStrainNumber: "",
    TypeOfDNAOrRNA: "",
    Percentage: "",
    TemperatureOfHybridization: "",
    Mutants: "",
    MutationMethods: "",
    Hybrids: "",
    Plasmid: "",
    KillerPropertiesOfYeast: "",
  },
  GrowthConditions: {
    ConditionsForGrowthAndMaintenenceOnSolidMedia: "",
    ConditionsForGrowthInLiquidMedia: "",
    ConditionsForFruitingOrSporulation: "",
    ConditionsForGermination: "",
    CarbonSourcesTested: "",
    NitrogenSourcesTested: "",
    SingleCompoundTested: "",
    NutritionalRequirements: "",
    Deficiencies: "",
    TolerancesAndSensitivities: "",
    TemperatureRelationships: "",
    MaximumGrowthPH: "",
    MinimumGrowthPH: "",
    OptimalGrowthPH: "",
    LighConditions: "",
    OxygenRelationship: "",
    HeatResistence: "",
    EthanolConditions: "",
    SalinityRequirements: "",
    OptimalNaClConcentration: "",
    MinimumNaClConcentration: "",
    MaximumNaClConcentration: "",
    OptimumSugarConcentration: "",
    MinimumSugarConcentration: "",
    MaximumSugarConcentration: "",
    OsmophilyAndXerophily: "",
    WaterActivityConditions: "",
  },
  ChemistryAndEnzymes: {
    EnzymesProduced: "",
    DecompositionAndDeterioratingCapacities: "",
    MetabolitiesProduced: "",
    Biotransformations: "",
  },
  Medium: {
    MediumNumber: "",
    MediumName: "",
    MediumComposition: "",
    MediumPH: "",
  },
  Sequence: {
    AccessionNumber: "",
    TargetGene: "",
    Definition: "",
    SequencingMethod: "",
    Length: "",
    SequenceType: "",
    Source: "",
    Sequence: "",
  },
  Catalogue: {
    CatalogueName: "",
    CatalogueURL: "",
    CatalogueUpdateTime: "",
    ContactPersonOfCatalogue: "",
    ContactEmail: "",
    ContactAddress: "",
    ContactTelephone: "",
    ContactFax: "",
    NumberOfStrains: "",
  },
};
