export const LabelNameData = {
  Status: "Status",
  UpdateStatus: "Update Status",
  SecurityLevel: "Security Level",
  CoreDataSets: "Core Data Sets",
  Genus: "Genus",
  AccessionNumber: "Accession Number",
  OtherCollectionNumbers: "Other Collection Numbers",
  SpeciesEpithet: "Species Epithet",
  Author: "Author",
  OrganismType: "Organism Type",
  HistoryOfDeposit: "History of Deposit",
  DateOfIsolation: "Date of Isolation",
  IsolatedFrom: "Isolated From",
  GeographicOrigin: "Geographic Origin",
  Status: "Status",
  Medium: "Medium",
  PH: "PH",
  TemperatureAtCollection: "TemperatureAtCollection",
  Application: "Application",
  Literature: "Literature",
  OptimumGrowthTemperature: "Optimum Growth Temperature",
  MaximumGrowthTemperature: "Maximum Growth Temperature",
  MinimumGrowthTemperature: "Minimum Growth Temperature",
  Name: "Name",
  TaxonomyID: "Taxonomy ID",
  StrainAdministration: "Strain Administration",
  DateOfAccession: "Date of Accession",
  HerbariumNo: "Herbarium No",
  InternalIdentityCheck: "Internal Identity Check",
  ModeOfPreservation: "Mode of Preservation",
  BioHazardLevel: "Bio Hazard Level",
  RestrictionRemarks: "Restriction Remarks",
  CountryOfExport: "Country of Export",
  MTA: "MTA",
  DistributionRestriction: "Distribution Restriction",
  AnimalQuarantineNo: "Animal Quarantine No",
  PlantQuarantineNo: "Plant Quarantine No",
  FormOfSupply: "Form of Supply",
  EnviromentAndHistory: "Enviroment and History",
  SubStrate: "Sub Strate",
  Habitat: "Habitat",
  Latitude: "Latitude",
  Longitude: "Longitude",
  Altitude: "Altitude",
  Depth: "Depth",
  Humidity: "Humidity",
  PHForEnviroment: "PH for Enviroment",
  TemperatureForEnviroment: "Temperature For Enviroment",
  CollectionMethod: "Collection Method",
  DateOfCollection: "Date of Collection",
  CountryOfCollection: "Country of Collection",
  State: "State",
  RegionOfCollection: "Region of Collection",
  CollectedBy: "Collected by",
  IsolatedBy: "Isolated by",
  MethodOfIsolation: "Method of Isolation",
  IdentifiedBy: "Identified By",
  DateOfIdentification: "Date of Identification",
  DepositedBy: "Deposited By",
  DateOfDeposition: "Date of Deposition",
  NameAtAccept: "Name at Accept",
  Publication: "Publication",
  LiteratureCategories: "Literature Categories",
  Title: "Title",
  Author: "Author",
  Journal: "Journal",
  Volume: "Volume",
  Number: "Number",
  StartingPage: "Starting Page",
  EndingPage: "Ending Page",
  PageRange: "Page Range",
  NumberOfNuclie: "Number of Nuclie",
  RehydrationFluid: "Rehydration Fluid",
  Matingtype: "Mating Type",
  KillerProperties: "Killer Properties",
  ConditionsForGrowthAndMaintenanceOnSolidMedia:
    "Conditions for Growth and Maintenance on Solid Media",
  ConditionsForGrowthAndMaintenanceOnLiquidMedia:
    "Conditions for Growth and Maintenance on Liquid Media",
  HeatResistance: "Heat Resistance",
  LightConditions: "LightConditions",

  Year: "Year",
  DOINumber: "DOI Number",
  BiologicalInteractions: "Biological Interactions",
  Symbiosis: "Symbiosis",
  Microparasitism: "Mycoparasitism",
  Pathogenicity: "Pathogenicity",
  Allergenicity: "Allergenicity",
  OtherOrganismsToxicity: "Other Organism Toxicity",
  AntagonisticActivities: "Antagonistic Activities",
  Sexuality: "Sexuality",
  SexualBehaviour: "Sexual Behaviour",
  SexualState: "Sexual State",
  Properties: "Properties",
  NumberOfNuclei: "Number of Nuclei",
  RehyderationFluid: "Rehyderation Fluid",
  FineStructureData: "Fine Structure Data",
  WallConstituents: "Wall Constituents",
  CellContents: "Cell Contents",
  CoenzymeQSystem: "Coenzyme Q System",
  StainingReactions: "Staining Reactions",
  PigmentProduction: "Pigment Production",
  CellShape: "Cell Shape",
  CellSize: "Cell Size",
  Motile: "Motile",
  SporeForming: "Spore Forming",
  MotileBy: "Motile By",
  GrnotypeAndGenetics: "Grnotype and Genetics",
  GenotypeAndGenetics: "Genotype and Genetics",
  Genotype: "Genotype",
  Phenotype: "Phenotype",
  MatingType: "Mating Type",
  SexualReproduction: "Sexual Reproduction",
  GCContentOfDNA: "GC Content of DNA",
  OtherStrainsHybridization: "Other Strains Hybridization",
  HybridizationStrainNumber: "Hybridization Strain Number",
  TypeOfDNAOrRNA: "Type of DNA or RNA",
  Percentage: "Percentage",
  TemperatureOfHybridization: "Temperature of Hybridization",
  Mutants: "Mutants",
  MutationMethods: "Mutation Methods",
  Hybrids: "Hybrids",
  Plasmid: "Plasmid",
  KillerPropertiesOfYeast: "Killer Properties of Yeast",
  GrowthConditions: "Growth Conditions",
  ConditionsForGrowthAndMaintenenceOnSolidMedia:
    "Conditions for Growth and MaintenenceOnSolidMedia",
  ConditionsForGrowthInLiquidMedia: "Conditions for Growth in Liquid Media",
  ConditionsForFruitingOrSporulation: "Conditions for Fruiting or Sporulation",
  ConditionsForGermination: "Conditions for Germination",
  CarbonSourcesTested: "Carbon Sources Tested",
  NitrogenSourcesTested: "Nitrogen Sources Tested",
  SingleCompoundsTested: "Single Compounds Tested",
  NutritionalRequirements: "Nutritional Requirements",
  MetabolitesProduced: "Metabolites Produced",
  TolerenceAndSensitivities: "Tolerence and Sensitivities",
  Deficiencies: "Deficiencies",
  TolerancesAndSensitivities: "Tolerances and Sensitivities",
  TemperatureRelationships: "Temperature Relationships",
  MaximumGrowthPH: "Maximum Growth PH",
  MinimumGrowthPH: "Minimum Growth PH",
  OptimalGrowthPH: "Optimal Growth PH",
  LighConditions: "Ligh Conditions",
  OxygenRelationship: "Oxygen Relationship",
  HeatResistence: "Heat Resistence",
  EthanolConditions: "Ethanol Conditions",
  SalinityRequirements: "Salinity Requirements",
  OptimalNaClConcentration: "Optimal NaCl Concentration",
  MinimumNaClConcentration: "Minimum NaCl Concentration",
  MaximumNaClConcentration: "Maximum NaCl Concentration",
  OptimumNaClContentration: "Optimum NaCl Contentration",
  OptimumSugarConcentration: "Optimum Sugar Concentration",
  MinimumSugarConcentration: "Minimum Sugar Concentration",
  MaximumSugarConcentration: "Maximum Sugar Concentration",
  OsmophilyAndXerophily: "Osmophily and Xerophily",
  WaterActivityConditions: "Water Activity Conditions",
  ChemistryAndEnzymes: "Chemistry and Enzymes",
  EnzymesProduced: "Enzymes Produced",
  DecompositionAndDeterioratingCapacities:
    "Decomposition and Deteriorating Capacities",
  MetabolitiesProduced: "Metabolities Produced",
  Biotransformations: "Biotransformations",
  Medium: "Medium",
  MediumNumber: "Medium Number",
  MediumName: "Medium Name",
  MediumComposition: "Medium Composition",
  MediumPH: "Medium PH",
  Sequence: "Sequence",
  AccessionNumber: "Accession Number",
  TargetGene: "TargetGene",
  Definition: "Definition",
  SequencingMethod: "Sequencing Method",
  Length: "Length",
  Sequencetype: "Sequence Type",
  Source: "Source",
  Sequence: "Sequence",
  Catalogue: "Catalogue",
  CatalogueName: "Catalogue Name",
  CatalogueURL: "Catalogue URL",
  CatalogueUpdateTime: "Catalogue Update Time",
  ContactPersonOfCatalogue: "Contact Person of Catalogue",
  ContactEmail: "Contact Email",
  ContactAddress: "Contact Address",
  ContactTelephone: "Contact Telephone",
  ContactFax: "Contact Fax",
  NumberOfStrains: "Number of Strains",

  // Genus: "",
  // AccessionNumber: "",
  // OtherCollection: [],
  // SpeciesEpithet: "",
  // Author: "",
  // OrganismType: "Bacteria",
  // HistoryOfDeposit: "",
  // DateOfIsolation: "",
  // IsolatedFrom: "",
  // GeographicOrigin: "",
  // Status: "Type",
  // Medium: "",
  // Application: "",
  // Literature: "",
  // OptimumGrowthTemperature: "",
  // MaximumGrowthTemperature: "",
  // MinimumGrowthTemperature: "",
  // TaxonomyID: "",
  // DateOfAccession: "",
  // HerbariumNo: "",
  // InternalIdentityCheck: "",
  // ModeOfPreservation: "",
  // BioHazardLevel: "1",
  // RestrictionRemarks: "",
  // CountryOfExport: "",
  // MTA: "",
  // DistributionRestriction: "",
  // AnimalQuarantineNo: "",
  // PlantQuarantineNo: "",
  // FormOfSupply: "",
  // SubStrate: "",
  // Habitat: "",
  // Latitude: "",
  // Longitude: "",
  // Altitude: "",
  // Depth: "",
  // Humidity: "",
  // PHForEnviroment: "",
  // TemperatureForEnviroment: "",
  // CollectionMethod: "",
  // DateOfCollection: "",
  // CountryOfCollection: "",
  // State: "",
  // RegionOfCollection: "",
  // CollectedBy: "",
  // IsolatedBy: "",
  // MethodOfIsolation: "",
  // IdentifiedBy: "",
  // DateOfIdentification: "",
  // DepositedBy: "",
  // DateOfDeposition: "",
  // NameAtAccept: "",
  // LiteratureCategories: "",
  // Title: "",
  // Author: "",
  // Journal: "",
  // Volume: "",
  // Number: "",
  // StartingPage: "",
  // PageRange: "",
  // Year: "",
  // DOINumber: "",
  // Symbiosis: "",
  // Mycoparasitism: "",
  // Pathogenicity: "",
  // Allergenicity: "",
  // OtherOrganismToxicity: "",
  // AntagonisticActivities: "",
  // SexualBehaviour: "",
  // SexualState: "",
  // NumberOfNuclei: "",
  // RehyderationFluid: "",
  // FineStructureData: "",
  // WallConstituents: "",
  // CellContents: "",
  // CoenzymeQSystem: "",
  // StainingReactions: "Positive",
  // PigmentProduction: "",
  // CellShape: "",
  // CellSize: "",
  // Motile: "Motile",
  // SporeForming: "",
  // MotileBy: "",
};
