exports.CoreDataSetsColumns = [
  { header: "Strain number", key: "AccessionNumber" },
  { header: "Other collection numbers", key: "OtherCollectionNumbers" },
  { header: "Genus_Name", key: "Genus" },
  { header: "Species_Epithet", key: "SpeciesEpithet" },
  { header: "Subspecies_Name", key: "SpeciesEpithet" },
  { header: "Author", key: "Author" },
  { header: "Organism_Type", key: "OrganismType" },
  { header: "History_of_Deposit", key: "HistoryOfDeposit" },
  { header: "Date_of_Isolation", key: "DateOfIsolation" },
  { header: "Isolated_From", key: "IsolatedFrom" },
  { header: "Geographic_Origin", key: "GeographicOrigin" },
  { header: "Status", key: "Status" },
  { header: "Optimum_Temperature_for_Growth", key: "OptimumGrowthTemperature" },
  { header: "Maximum_Temperature_for_Growth", key: "MaximumGrowthTemperature" },
  { header: "Minimum_Temperature_for_Growth", key: "MinimumGrowthTemperature" },
  { header: "Medium", key: "Medium" },
  { header: "Application", key: "Application" },
  { header: "Literature", key: "Literature" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.nameColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "TaxonomyID", key: "TaxonomyID" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.StrainAdministrationColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Date of accession", key: "DateOfAccession" },
  { header: "Herbarium No", key: "HerbariumNo" },
  {
    header: "Internal check of identity at collection",
    key: "InternalIdentityCheck",
  },
  { header: "Mode of preservation / storage", key: "ModeOfPreservation" },
  { header: "Bio hazard level", key: "BioHazardLevel" },
  { header: "Remarks on Restrictions", key: "RestrictionRemarks" },
  { header: "Country of export", key: "CountryOfExport" },
  { header: "MTA", key: "MTA" },
  { header: "Restriction for destribute", key: "DestributionRestriction" },
  { header: "Animal quarantine No", key: "AnimalQuarantineNo" },
  { header: "Plant Quanrantine No", key: "PlantQuarantineNo" },
  { header: "Form of supply", key: "FormOfSupply" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.EnviromentAndHistoryColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Substrate", key: "SubStrate" },
  { header: "Habitat", key: "Habitat" },
  { header: "latitude", key: "Latitude" },
  { header: "longitude", key: "Longitude" },
  { header: "Altitude", key: "Altitude" },
  { header: "Depth", key: "Depth" },
  { header: "Humidity for enviroment", key: "Humidity" },
  { header: "PH for enviroment", key: "PH" },
  { header: "Temperature for enviroment", key: "TemperatureAtCollection" },
  { header: "Collection method", key: "CollectionMethod" },
  { header: "Date of Collection", key: "DateOfCollection" },
  { header: "Country", key: "CountryOfCollection" },
  { header: "State", key: "CountryOfCollection" },
  { header: "Region", key: "RegionOfCollection" },
  { header: "Collected by", key: "CollectedBy" },
  { header: "Isolated by", key: "IsolatedBy" },
  { header: "method of isolation", key: "MethodOfIsolation" },
  { header: "Identified by", key: "IdentifiedBy" },
  { header: "Date of Identification", key: "DateOfIdentification" },
  { header: "Deposited by", key: "DepositedBy" },
  { header: "Date of deposition", key: "DateOfDeposition" },
  { header: "Name at accept", key: "NameAtAccept" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.PublicationColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Literature Categories", key: "LiteratureCategories" },
  { header: "Title", key: "Title" },
  { header: "Author", key: "Author" },
  { header: "Journal", key: "Journal" },
  { header: "Volume", key: "Volume" },
  { header: "Number", key: "Number" },
  { header: "StartingPage", key: "StartingPage" },
  { header: "PageRange", key: "EndingPage" },
  { header: "Year", key: "Year" },
  { header: "DOI Number", key: "DOINumber" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.BiologicalinteractionsColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Symbiosis", key: "Symbiosis" },
  { header: "Mycoparasitism", key: "Microparasitism" },
  { header: "Pathogenicity", key: "Pathogenicity" },
  { header: "Allergenicity", key: "Allergenicity" },
  { header: "Toxicity to other organisms", key: "OtherOrganismsToxicity" },
  {
    header: "Antagonistic activities against other organisms",
    key: "AntagonisticActivities",
  },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.SEXUALITYColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Sexual behaviour", key: "SexualBehaviour" },
  { header: "Sexual state", key: "SexualState" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.PropertiesColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Number of nuclei", key: "NumberOfNuclie" },
  { header: "Rehydration Fluid", key: "RehydrationFluid" },
  { header: "Fine structure data", key: "FineStructureData" },
  { header: "Wall constituents", key: "WallConstituents" },
  { header: "Cell contents", key: "CellContents" },
  { header: "Coenzyme-Q system", key: "CoenzymeQSystem" },
  { header: "Staining reactions", key: "StainingReactions" },
  {
    header: "Pigment production and autofluorescence",
    key: "PigmentProduction",
  },
  { header: "CellShape", key: "CellShape" },
  { header: "CellSize", key: "CellSize" },
  { header: "Motile", key: "Motile" },
  { header: "SporeForming", key: "SporeForming" },
  { header: "MotileBy", key: "MotileBy" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];

exports.GrnotypeAndGeneticsColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Genotype", key: "Genotype" },
  { header: "Phenotype", key: "Phenotype" },
  { header: "Mating type", key: "Matingtype" },
  { header: "Sexual reproduction", key: "SexualReproduction" },
  { header: "GC content of DNA", key: "GCContentOfDNA" },
  {
    header: "Hybridization with other strains",
    key: "OtherStrainsHybridization",
  },
  { header: "Hybridization strain number", key: "HybridizationStrainNumber" },
  { header: "Type of DNA or RNA", key: "TypeOfDNAOrRNA" },
  { header: "Percentage", key: "Percentage" },
  { header: "Temperature of Hybridization", key: "TemperatureOfHybridization" },
  { header: "Mutants", key: "Mutants" },
  { header: "Method by which mutation was induced", key: "MutationMethods" },
  { header: "Hybrids", key: "Hybrids" },
  { header: "Plasmid", key: "Plasmid" },
  { header: "Killer properties of yeast", key: "KillerProperties" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.GrowteConditionsColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  {
    header: "Conditions for growth and maintenance on solid media",
    key: "ConditionsForGrowthAndMaintenanceOnSolidMedia",
  },
  {
    header: "Conditions for growth in liquid media",
    key: "ConditionsForGrowthAndMaintenanceOnLiquidMedia",
  },
  {
    header: "Conditions for fruiting or sporulation",
    key: "ConditionsForFruitingOrSporulation",
  },
  { header: "Conditions for germination", key: "ConditionsForGermination" },
  {
    header: "Carbon sources that have been tested for growth",
    key: "CarbonSourcesTested",
  },
  {
    header: "Nitrogen sources that have been tested for growth",
    key: "NitrogenSourcesTested",
  },
  {
    header:
      "Single compounds tested as sole carbon and nitrogen source for growth",
    key: "SingleCompoundsTested",
  },
  {
    header: "Nutritional requirements and growth factors required",
    key: "NutritionalRequirements",
  },
  { header: "Deficiencies", key: "Deficiencies" },
  { header: "Tolerances and sensitivities", key: "TolerenceAndSensitivities" },
  {
    header: "Temperature relationships for growth",
    key: "TemperatureRelationships",
  },
  { header: "Maximum growth PH", key: "MaximumGrowthPH" },
  { header: "Minimum growth PH", key: "MinimumGrowthPH" },
  { header: "optimal growth PH", key: "OptimalGrowthPH" },
  { header: "Light conditions", key: "LightConditions" },
  { header: "Oxygen relationship", key: "OxygenRelationship" },
  { header: "Heat resistance", key: "HeatResistance" },
  { header: "Ethanol conditions", key: "EthanolConditions" },
  { header: "Salinity requirements for growth", key: "SalinityRequirements" },
  {
    header: "Optimum/Minimum/Maximum NaCl concentration",
    key: "OptimumNaClContentration",
  },
  {
    header: "Optimum/Minimum/Maximum sugar concentrations",
    key: "OptimumSugarContentration",
  },
  { header: "Osmophily and xerophily", key: "OsmophilyAndXerophily" },
  { header: "Conditions of water activity", key: "WaterActivityConditions" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.ChemistryAndEnzymesColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Enzymes produced", key: "EnzymesProduced" },
  {
    header: "Decomposition and deteriorating capacities",
    key: "DecompositionAndDeterioratingCapacities",
  },
  { header: "Metabolites produced ", key: "MetabolitesProduced" },
  { header: "Biotransformations", key: "Biotransformations" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.MediumColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "mediumNumber", key: "MediumNumber" },
  { header: "mediumName", key: "MediumName" },
  { header: "mediumComposition", key: "MediumComposition" },
  { header: "Medium PH", key: "MediumPH" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.SequenceColumns = [
  { header: "Strain Number", key: "AccessionNumber" },
  { header: "Accesion number", key: "AccessionNumber" },
  { header: "Target gene", key: "TargetGene" },
  { header: "Definition", key: "Definition" },
  { header: "Sequencing method", key: "SequencingMethod" },
  { header: "Length", key: "Length" },
  { header: "Sequence type", key: "Sequencetype" },
  { header: "Source", key: "Source" },
  { header: "Sequence", key: "Sequence" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
exports.CatlogueColumns = [
  { header: "Catalogue Name", key: "CatalogueName" },
  { header: "Catalogue URL", key: "CatalogueURL" },
  { header: "Catalogue Update Time", key: "CatalogueUpdateTime" },
  { header: "Contact person of Catalogue", key: "ContactPersonOfCatalogue" },
  { header: "Contact E-Mail", key: "ContactEmail" },
  { header: "Contact address", key: "ContactAddress" },
  { header: "Contact TEL", key: "ContactTelephone" },
  { header: "Contact FAX", key: "ContactFax" },
  { header: "Number of Strains in Catalogue", key: "NumberOfStrains" },
  { header: "Security_Level", key: "SecurityLevel" },
  { header: "Update_Status", key: "UpdateStatus" },
];
